### ISSUE TITLE
Allow strafing with dominant hand thumb stick

### ISSUE THREAD

**Issue by peanutismint** [DrBeef/Quake2Quest#1]
Great work with this port!! Sorry if there's a way to do this already that I'm missing but would it be possible to allow strafing with the dominant hand thumb stick/turning with the non-dominant hand thumbstick? Basically the opposite of what's currently mapped. Thanks!

**Comment by neitey** [comment]
That would be a rather unusual control scheme i guess. Never played a VR game that uses that kind of controls.

**Comment by peanutismint** [comment]
I've played plenty of games that offer it as an option. Halo, GoldenEye, Call Of Duty - pretty much any shooter that allows gamepad/thumbstick control. They used to call it 'Southpaw' and it feels more natural to me, even though I'm right-handed....

**Comment by DrBeef** [comment]
Maybe in a future version if I do add Yamagi support
