### ISSUE TITLE
Request: smooth turning

### ISSUE THREAD

**Issue by mycelo1** [DrBeef/Quake2Quest#15]
The snap turning isn't great on first-person shooters. Also, when snap-turning, the weapons takes a split second to actually relocate, which is very distracting.

**Comment by baggyg** [comment]
From the website: 
You can set a cvar in the config.cfg in the following manner:
set vr_snapturn_angle "5"

vr_snapturn_angle - Sets the angle of the snap turn, set to a value < 10 for smooth turning

**Comment by mycelo1** [comment]
Thanks for your patience, I'm stupid. That worked beautifully.
