### ISSUE TITLE
cant copy quake2quest to oculus

### ISSUE THREAD

**Issue by alwzfolwd** [DrBeef/Quake2Quest#17]
when i try to copy the quake2quest zip to the oculus it fails with an error saying that there is no installable file in the zip. what do i do or am i doing something wrong? im trying to copy the zip to the oculus using sidequest.. should i be doing it a different way?

**Comment by baggyg** [comment]
You need to copy the APK file if installing manually, not the zip file. 

However if using Sidequest much easier just to click the "Sideload" button on the listing:
https://sidequestvr.com/app/353/quake2quest

You can find full instructions here:
https://quake2quest.quakevr.com/index.php

**Comment by alwzfolwd** [comment]
Thanks a bunch!
