### ISSUE TITLE
Turn off "snap turn"

### ISSUE THREAD

**Issue by KyokushinPL** [DrBeef/Quake2Quest#18]
Hi, 
Any way to turn off the 'snap turn'? I would like to use 'continuos' way of rotating.

**Comment by baggyg** [comment]
You should put these in the config.cfg file that is located in the Quake2Quest folder on the Oculus Quest

You can set a cvar in the config.cfg in the following manner:
set vr_snapturn_angle "5"

vr_snapturn_angle - Sets the angle of the snap turn, set to a value < 10 for smooth turning

https://quake2quest.quakevr.com/index.php
