### ISSUE TITLE
Difficulty changing weapons

### ISSUE THREAD

**Issue by kgian** [DrBeef/Quake2Quest#2]
When I press up/down on the right thumb stick to change weapons sometimes I snap turn instead. Changing weapons feels sluggish and imprecise. The same happens when I try to change them through the menu. Maybe dead zones need to be tweaked or there has to be an option to disable turning with the thumb stick.

**Comment by DrBeef** [comment]
>  Changing weapons feels sluggish and imprecise.

That's just how long it takes for the weapon to switch, it's the holster and deploy animations. Guess I could speed them up a bit, but that's not a high priority.

>   there has to be an option to disable turning with the thumb stick.

There is.. set vr_snapturn_angle "0"
