### ISSUE TITLE
Version 1.0 Yamagi is missing the comfort mask png file.

### ISSUE THREAD

**Issue by neitey** [DrBeef/Quake2Quest#4]
The comfort mask is not working in the lastest version 1.0. Shows only a white square. Seems like the png picture for the mask is missing.

**Comment by DrBeef** [comment]
I found if you copy the vignette.tga file from the assets folder in this repo to the /Quake2Quest folder it will work (as a workaround), but I need to fix this properly.

**Comment by neitey** [comment]
Great, already commented that workaround to the person asking on reddit.

Am Do., 19. Dez. 2019 um 14:53 Uhr schrieb Simon <notifications@github.com>:

**Comment by neitey** [comment]
Fixed
