### ISSUE TITLE
Suggestion to help reduce motion sickness

### ISSUE THREAD

**Issue by redcurry** [DrBeef/Quake2Quest#6]
Thank you for this port, it's amazing! I just have one suggestion: allow the player to teleport a few steps forward rather than move continuously. I think this would help reduce motion sickness.

**Comment by BenMcLean** [comment]
Can't change the game's basic rules.

**Comment by tfactor2** [comment]
Great port indeed!
Still can’t play more than couple of mins(

What about adding a vignette?

**Comment by DrBeef** [comment]
There is a comfort vignette.. look in the options menu, it's in there somewhere (configurable strength).
