### ISSUE TITLE
Request: Optional Smooth Turn

### ISSUE THREAD

**Issue by raum-dellamorte** [DrBeef/Quake2Quest#9]
Snap Turns and Teleport movement in VR games drive me insane. VR games _should_ default to "Comfort" settings like that, but not having an option to turn them off is maddening.  I plan on forking the repo and trying to add optional smooth turning myself, but I would not be upset if you were to add it.

That said, your greatness will be known throughout the ages for the port!

**Comment by DrBeef** [comment]
This is (or should be) already possible, the option isn't in the menu, but if you edit the config file and set vr_snapturn_angle to a value < 10 then it will actually use smooth turning. It will turn you the specified number of degrees per frame, so obviously the higher the number (up to 10) the faster you will turn, so pick your most comfortable number and use that. something like 2 or 3 is probably ideal.

If that doesn't work for you please let me know and I'll take a look, for now I will close this issue.
